name: Deploy
on: push
jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: snakemake/snakemake-github-action@v2
        with:
          directory: .
          snakefile: 'workflow/Snakefile'
          args: '--use-conda --conda-cleanup-pkgs cache -p --cores 4 --verbose'
          stagein: ''
          show-disk-usage-on-error: true
      - run: |
          mkdir upload
          cd output/results
          tar -czvf test-data.tgz *
          mv test-data.tgz ../upload/.
      - if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/')
        name: Upload test data to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: 'output/upload/test-data.tgz'
          tag: ${{ github.ref }}
          overwrite: true